-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2012.4
-- Copyright (C) 2012 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Sobel is
port (
    nResetPort : IN STD_LOGIC;
    ClockPort : IN STD_LOGIC;
    fifo_in_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifo_in_0_empty_n : IN STD_LOGIC;
    fifo_in_0_read : OUT STD_LOGIC;
    fifo_out_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifo_out_0_full_n : IN STD_LOGIC;
    fifo_out_0_write : OUT STD_LOGIC );
end;


architecture behav of Sobel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Sobel,hls_ip_2012_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.908000,HLS_SYN_LAT=39966,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=309,HLS_SYN_LUT=583}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal grp_Sobel_thread_fu_58_fifo_in_0_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Sobel_thread_fu_58_fifo_in_0_empty_n : STD_LOGIC;
    signal grp_Sobel_thread_fu_58_fifo_in_0_read : STD_LOGIC;
    signal grp_Sobel_thread_fu_58_fifo_out_0_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Sobel_thread_fu_58_fifo_out_0_full_n : STD_LOGIC;
    signal grp_Sobel_thread_fu_58_fifo_out_0_write : STD_LOGIC;

    component Sobel_thread IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        fifo_in_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifo_in_0_empty_n : IN STD_LOGIC;
        fifo_in_0_read : OUT STD_LOGIC;
        fifo_out_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fifo_out_0_full_n : IN STD_LOGIC;
        fifo_out_0_write : OUT STD_LOGIC );
    end component;



begin
    grp_Sobel_thread_fu_58 : component Sobel_thread
    port map (
        ap_clk => ClockPort,
        ap_rst => nResetPort,
        fifo_in_0_dout => grp_Sobel_thread_fu_58_fifo_in_0_dout,
        fifo_in_0_empty_n => grp_Sobel_thread_fu_58_fifo_in_0_empty_n,
        fifo_in_0_read => grp_Sobel_thread_fu_58_fifo_in_0_read,
        fifo_out_0_din => grp_Sobel_thread_fu_58_fifo_out_0_din,
        fifo_out_0_full_n => grp_Sobel_thread_fu_58_fifo_out_0_full_n,
        fifo_out_0_write => grp_Sobel_thread_fu_58_fifo_out_0_write);



    fifo_in_0_read <= grp_Sobel_thread_fu_58_fifo_in_0_read;
    fifo_out_0_din <= grp_Sobel_thread_fu_58_fifo_out_0_din;
    fifo_out_0_write <= grp_Sobel_thread_fu_58_fifo_out_0_write;
    grp_Sobel_thread_fu_58_fifo_in_0_dout <= fifo_in_0_dout;
    grp_Sobel_thread_fu_58_fifo_in_0_empty_n <= fifo_in_0_empty_n;
    grp_Sobel_thread_fu_58_fifo_out_0_full_n <= fifo_out_0_full_n;
end behav;
